# Generated by Django 4.2.2 on 2023-08-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_link_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Red',
        ),
        migrations.AddField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='bajada',
            field=models.CharField(max_length=150, verbose_name='Bajada'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=250, unique=True, verbose_name='Título'),
        ),
    ]
